### ISSUE TITLE
Prometheus plugin doesn't work with 2.6.0-beta1

### ISSUE THREAD

**Issue by atombender** [grafana/grafana-plugins#58]
These may be problems with the beta, who knows.

Grafana's backend looks for `/usr/share/grafana/public/app/plugins/datasource/prometheus/datasource.js`, but the frontend tries to load it from `/usr/share/grafana/public/plugins/datasource/prometheus/datasource.js` (notice missing "app"), which results in a 404. Symlinking seems to fix the issue.

Prometheus then tries to load `kbn.js`, which is no longer in the root, but in `public/app/core/utils/kbn.js`.

`kbn.js` has apparently changed, and you now get:

```
Error: kbn.parseDate is not a function. (In 'kbn.parseDate($scope.dashboard.time.from)', 'kbn.parseDate' is undefined)
```

**Comment by mtanda** [comment]
From version 2.5, Grafana officially support Prometheus.
The plugin in this repos is not maintained.
Please use plugin in grafana/grafana. (You don't need extra plugin, it's included in release package)
http://grafana.org/blog/2015/10/28/Grafana-2-5-Released.html

**Comment by mtanda** [comment]
@torkelo please merge this PR, https://github.com/grafana/grafana-plugins/pull/50 . (removing plugin code from grafana/grafana-plugins)

**Comment by atombender** [comment]
Ah, I didn't know. Thanks!

**Comment by mtanda** [comment]
@atombender Would you close this issue?
